### ISSUE TITLE
Make project multi-module

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#10]
We need the following modules:

 - `core`, which contains the core data types
 - `driver`, which contains the ZIO definitions of database operations, independent of a backend
 - `jdbc`, which contains a lowest-common denominator JDBC "driver" for the ZIO definitions, which assumes ANSI-92 compliance
 - `postgres`, which contains a Postgres dialect and driver
 - `mysql`, which contains a Postgres dialect and JDBC-based driver
 - `sqlserver`, which contains a SQL Server dialect and JDBC-based driver
 - `oracle`, which contains an Oracle dialect and JDBC-based driver
 - `spark`, which contains a Spark SQL dialect and Spark-based driver
 - `cassandra`, which contains a Cassandra SQL dialect and Cassandra-based driver
 - `test`, which contains a test "driver" for the ZIO definitions

We can probably start with just `core`, `driver`, `jdbc`, and `test`.

This ticket involves only creating the SBT project structure and directory structure, not implementing any modules.

**Comment by jczuchnowski** [comment]
I'll take this one.
