### ISSUE TITLE
Consider a git pre-commit hook to call scalafmt

### ISSUE THREAD

**Issue by oranda** [zio/zio-sql#106]
The CI is repeatedly showing build failures at the `scalafmtCheck` stage. I guess that is because developers are forgetting to call `fmt` in sbt before committing? 

Formatting can be automated with a git pre-commit or pre-push hook. The approach is not universally popular, but it is described here:

https://medium.com/zyseme-technology/code-formatting-scalafmt-and-the-git-pre-commit-hook-3de71d099514

**Comment by oranda** [comment]
On second thoughts, a simpler solution might be to add this to `build.sbt`:
```
scalafmtOnCompile := true
```

There was also discussion of this here:

https://github.com/zio/zio/pull/2039#issuecomment-546730611

In that case the CI was not broken, so the issue was closed.

**Comment by jczuchnowski** [comment]
@oranda I've enabled the lint step in the CI pipeline, so we're now checking the formatting before the PR can be merged. This is in line with othe ZIO projects I believe. Is this satisfactory?

**Comment by oranda** [comment]
Sounds great. Close this issue when you like.
