### ISSUE TITLE
Render all table and column names in double quotes in PostgreSQL

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#142]
Modify `PostgresModule#renderRead` so that the queries it renders are case sensitive. 

For example:
```sql
select users.first_name, users.last_name from users
```
should become
```sql
select "users"."first_name", "users"."last_name" from "users"
```

We will also need appropriate tests in `PostgresModuleTest` that will prove uppercased db objects can be correctly queried from ZIO SQL.

**Comment by katlasik** [comment]
I can pick that one for hackaton
