### ISSUE TITLE
Create DELETE query examples

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#15]
We need a few examples of DELETE queries under different schemas, both to validate the design and flesh out edge cases, as well as to show people how to use the data type to model DELETE queries.

**Comment by unclebob418** [comment]
I'll take this one and  #12 #13 #14 #16 - I'll need these for #8 and will probably come up with more edge cases from doing that. From watching the video I'm 90% sure I can write at least queries that will compile but won't be valid sql and vice versa. I also have some suspicions on group by.
`delete from a left join b on a.id = b.id where b.c = d` this isn't valid but I think will probably compile
`delete a from a left join b on a.id = b.id where b.c = d` this is valid but I don't think we can currently form this statement
guess I'll find out soon enough!

**Comment by jdegoes** [comment]
Awesome, appreciate the identification of edge cases too!

**Comment by jczuchnowski** [comment]
@robmwalsh can this issue be closed (and related mentioned by you)?

**Comment by robmwalsh** [comment]
The reason it was originally left open was because the issue requested "under multiple schemas", but I'm not sure we need additional schemas - I think there's enough there to do most queries you're going to see in the wild.

**Comment by jczuchnowski** [comment]
Ok, so I think I'll close these issues, as it's getting harder and harder to keep up with what is actually to do.
And yeah, I think the current examples are sufficient for now and we can expand them as needed.
