### ISSUE TITLE
Add 'factorial' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#172]
Add support for function `factorial` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-math.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by shankarshastri** [comment]
@jczuchnowski , I would like to tackle this problem.

**Comment by shankarshastri** [comment]
@jczuchnowski , how should we handle in general for numeric types? Because we could only have one FunctionDef. Can you please help me on the same?
