### ISSUE TITLE
Add infrastructure for testing against Postgres

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#18]
We will soon need to run tests against Postgres. To prepare for this, we can modify the CircleCI continuous build to install Postgres, and possibly add a helper script(s) to install Postgres locally so developers who run locally tests can have a local install of the database for testing purposes.

- [x] Have helper SBT command that can install Postgres locally on developer machines
- [ ] Modify CircleCI build to install Postgres

This ticket will be complete when a small ZIO Test is added into a `postgres` project that verifies a local Postgres database can be connected to. This will be enough functionality to begin developing test suites against Postgres.

**Comment by hmemcpy** [comment]
Having just [written a blog post](https://hmemcpy.com/2020/10/running-postgres-integration-tests-easily-with-testcontainers-and-zio-test/) about integrating Postgres into ZIO Tests, would a suite that runs with embedded docker containers work? Each test gets a fresh container, with an optional migration step to set up the schemas. Pretty fast, too.

**Comment by jczuchnowski** [comment]
Did exactly that with the help of your blog post. Thanks @hmemcpy !
