### ISSUE TITLE
Add 'format' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#184]
Add support for function `format` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-string.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by angelicarao** [comment]
I'd like to work on this one

**Comment by TobiasPfeifer** [comment]
working on this
