### ISSUE TITLE
Add 'md5' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#189]
Add support for function `md5` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-string.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by riccardocorbella** [comment]
I'd like to try to work on this one. :)

**Comment by Porcupine96** [comment]
@riccardocorbella 

Fun fact, if you were copy the example from the Postgres documentation of `md5` there's an empty space character.

Returned: 
`9(57) 0(48) 0(48) 1(49) 5(53) 0(48) 9(57) 8(56) 3(51) c(99) d(100) 2(50) 4(52) f(102) b(98) 0(48) d(100) 6(54) 9(57) 6(54) 3(51) f(102) 7(55) d(100) 2(50) 8(56) e(101) 1(49) 7(55) f(102) 7(55) 2(50)`

Expected (copied from docs):
9(57) 0(48) 0(48) 1(49) 5(53) 0(48) 9(57) 8(56) 3(51) c(99) d(100) 2(50) 4(52) f(102) b(98) 0(48) (**8203**) d(100) 6(54) 9(57) 6(54) 3(51) f(102) 7(55) d(100) 2(50) 8(56) e(101) 1(49) 7(55) f(102) 7(55) 2(50)

It took me a while to figure why the test did not pass.
