### ISSUE TITLE
Add infrastructure for testing against Mysql

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#19]
We will soon need to run tests against MySQL. To prepare for this, we can modify the CircleCI continuous build to install MySQL, and possibly add a helper script(s) to install MySQL locally so developers who run locally tests can have a local install of the database for testing purposes.

- [x] Have helper SBT command that can install MySQL locally on developer machines
- [ ] Modify CircleCI build to install MySQL

This ticket will be complete when a small ZIO Test is added into a `mysql` project that verifies a local MySQL database can be connected to. This will be enough functionality to begin developing test suites against MySQL.

**Comment by jczuchnowski** [comment]
We're switching to Testcontainers. This should be implemented analogically to how `PostgresModuleTest` is done.

**Comment by jczuchnowski** [comment]
Closing this. At this point it duplicates: https://github.com/zio/zio-sql/issues/69
