### ISSUE TITLE
Add 'parse_ident' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#190]
Add support for function `parse_ident` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-string.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by alim16** [comment]
dibs!
I'm new to this scala stuff so I'll give it a go, but I'm happy to accept any help
