### ISSUE TITLE
Add 'quote_ident' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#192]
Add support for function `quote_ident` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-string.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by riccardocorbella** [comment]
I'd like to work on this one.

**Comment by jczuchnowski** [comment]
This is still an open issue.
