### ISSUE TITLE
Add 'quote_nullable' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#194]
Add support for function `quote_nullable` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-string.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by pierangeloc** [comment]
I'll pick this one

**Comment by pierangeloc** [comment]
I have trouble figuring out the types that should be used to cope with this function, as in case of NULL input, it should produce NULL output.
The first thing I came up with is 

```scala
    def QuoteNullable[A: TypeTag.NotNull] = FunctionDef[Option[A], Option[String]](FunctionName("quote_nullable"))
```

However if I try to use it in test
```scala
    val q: Option[Double] = None
    val query = select(QuoteNullable(q)) from customers
```
it doesn't compile
```
[error] /Users/pierangelo.cecchetto/Documents/projects/myprojects/zio-sql/postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala:55:40: type mismatch;
[error]  found   : Option[Double]
[error]  required: zio.sql.postgresql.FunctionDefSpec.TypeTag.NotNull[?]
[error]       val query = select(QuoteNullable(q)) from customers
[error]                                        ^
```

WIP is here https://github.com/pierangeloc/zio-sql/tree/276-add-quote_nullable

This is the first time I look at this library, but it seems to me that `zio.sql.postgresql.PostgresModule#renderRead` is not dealing with Optional parameters, or am I missing something?

**Comment by jczuchnowski** [comment]
This doesn't seem like a useful function from the library perspective.
