### ISSUE TITLE
Add infrastructure for testing against SQL Server

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#20]
We will soon need to run tests against SQL Server. To prepare for this, we can modify the CircleCI continuous build to install SQL Server, and possibly add a helper script(s) to install SQL Server locally so developers who run locally tests can have a local install of the database for testing purposes.

- [x] Have helper SBT command that can install SQL Server locally on developer machines
- [ ] Modify CircleCI build to install SQL Server

This ticket will be complete when a small ZIO Test is added into a `sqlserver` project that verifies a local SQL Server database can be connected to. This will be enough functionality to begin developing test suites against SQL Server.

**Note**: _Looks like this will require docker._

**Comment by jczuchnowski** [comment]
We're switching to Testcontainers. This should be implemented analogically to how `PostgresModuleTest` is done.

**Comment by jczuchnowski** [comment]
Closing this. At this point it duplicates https://github.com/zio/zio-sql/issues/71
