### ISSUE TITLE
Add infrastructure for testing against Oracle

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#21]
We will soon need to run tests against Oracle. To prepare for this, we can modify the CircleCI continuous build to install Oracle (on supported platforms such as Windows, Linux, or Solaris), and possibly add a helper script(s) to install Oracle locally so developers who run locally tests can have a local install of the database for testing purposes.

- [x] Have helper SBT command that can install Oracle locally on developer machines
- [ ] Modify CircleCI build to install Oracle

This ticket will be complete when a small ZIO Test is added into a `oracle` project that verifies a local Oracle database can be connected to. This will be enough functionality to begin developing test suites against Oracle.

**Note**: _Oracle cannot be installed on Mac outside a VM_.

**Comment by jczuchnowski** [comment]
We're switching to Testcontainers. This should be implemented analogically to how `PostgresModuleTest` is done.

**Comment by jczuchnowski** [comment]
Closing this. At this point it duplicates https://github.com/zio/zio-sql/issues/70
