### ISSUE TITLE
Add 'make_*' functions to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#211]
Add support for functions `make_date`, `make_interval`, `make_time`, `make_timestamp`, `make_timestampz` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-datetime.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by brbrown25** [comment]
I can pick this up
