### ISSUE TITLE
Add 'localtime' and 'localtimestamp' functions to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#212]
Add support for functions `localtime` and `localtimestamp` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-datetime.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by riccardocorbella** [comment]
I pick this issue.
