### ISSUE TITLE
Add 'now', 'statement_timestamp' and 'transaction_timestamp' functions to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#213]
Add support for functions `now`, `statement_timestamp`, and `transaction_timestamp` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-datetime.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by xplosunn** [comment]
I'll do this one

**Comment by marekklis** [comment]
I'll take this
