### ISSUE TITLE
Add 'to_timestamp' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#215]
Add support for function `to_timestamp` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-datetime.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by brbrown25** [comment]
I'll pick this one up

**Comment by robmwalsh** [comment]
Fixed in #263
