### ISSUE TITLE
Introduce ZIO SQL "driver" interface

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#22]
The ZIO SQL driver interface will have:

 - `select`
 - `deleteFrom`
 - `update`
 - `insert`

and, possibly in the future, DDL.

These will return ZIO effects or ZIO streams, as appropriate.

This is expected to be a lightweight project at the top-level, on which JDBC / etc. projects will depend to expose CRUD functionality atop the core SQL query data model.

**Comment by jdegoes** [comment]
This is partially implemented. We have to figure out whether or not to combine the `ReadExecutor` / etc. interfaces into a single interface, or keep them separate.

**Comment by phderome** [comment]
note for `insert`. `returning` clause returning data to caller should be supported. See for example https://mariadb.com/kb/en/insertreturning/#:~:text=Description-,INSERT%20...,alternatively%2C%20the%20specified%20SELECT%20expression.

**Comment by sviezypan** [comment]
Mostly implemented, rest is in the issue #596
