### ISSUE TITLE
Add test for 'Replace' function for PostgreSQL

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#247]

**Comment by rpiotrow** [comment]
I would like to try solve this one.

**Comment by angelicarao** [comment]
@rpiotrow Did you manage to solve this? I'm having an [issue](https://github.com/zio/zio-sql/issues/246#issuecomment-731577346) with my ticket and I feel it might affect yours too.

**Comment by rpiotrow** [comment]
@angelicarao I made a MR, please take a look if it solves the problem you have encountered.
