### ISSUE TITLE
Create microsite for ZIO SQL

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#252]
Using Docusaurus and mdoc, following the conventions of ZIO, we should stand up a minimal microsite for ZIO SQL, with getting started and a few examples, with an eye toward expanding the content over time.

**Comment by xplosunn** [comment]
Gonna try to do this one

**Comment by aappddeevv** [comment]
I see there is a websit directory with a docusaurus instance of some sort.

@jczuchnowski Is the site there but just needs to get hooked up to github pages a bit better?

**Comment by sviezypan** [comment]
Done https://zio.github.io/zio-sql/
