### ISSUE TITLE
Add all binary operators supported by ANSI-92

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#3]
We should support the full set of binary operators, like `*`, `+`, etc., which are defined by ANSI-92 and / or supported by Postgres, MySQL, SQL Server, and Oracle.

These would be added as `BinaryOp` subtypes, with new methods defined in `Expr` like the methods for `*`, and `&&`.

If anything is unclear, please ask for more details!

**Comment by jczuchnowski** [comment]
I'll work on this.

**Comment by jdegoes** [comment]
@jczuchnowski Awesome, thank you!

**Comment by jczuchnowski** [comment]
As I move forward I will be putting here information about decisions I make and findings realated to differences between the databases.
For starters:
- `%` as a modulo operator is not supported by Oracle
- `^` as an exponentiation operator is not supported by MySQL
