### ISSUE TITLE
Support `select` statements without `from`

### ISSUE THREAD

**Issue by robmwalsh** [zio/zio-sql#323]
At the moment we need to select from a table, even if we have no requirement for a table
e.g. we can't execute `select 1`, but we can execute `select 1 from aTable`

Existing tests should be cleaned up to remove tables from queries where none are required, which should be proof enough that this works.

**Comment by TobiasPfeifer** [comment]
We could provide an implicit conversion from `SelectBuilder[F, Any, B]` to `Read.Select(Selection[F, A, B0], None, true, Nil)` where the second parameter for `Read.Select` becomes `Option[Table.Aux[Any]]` and is not rendert in the `None` case.

However type inference might not work too well with this approach. Any other ideas how to solve this while keeping the compile time check that the selection type matches the `TableType` in queries `select x from x.y;`

**Comment by TobiasPfeifer** [comment]
I created a draft of my idea: https://github.com/TobiasPfeifer/zio-sql/commit/784fdd47e438ce38541b3fcd2168260c0f7d743b

As I expected the additional implicit conversion doesn't play well with intelliJ (more red lines then before)
Other suggestions and discussions are welcome

**Comment by robmwalsh** [comment]
I wouldn't worry too much about IJ red squiggles. It's unlikely that people will actually use this often, but it'll tidy up the tests and should be supported since you can do it in SQL. Is this ready for review?

**Comment by TobiasPfeifer** [comment]
Need to tidy up some more specs and figure out why I can't compile [this `typeCheck` assertion](https://github.com/TobiasPfeifer/zio-sql/commit/784fdd47e438ce38541b3fcd2168260c0f7d743b#r49148360). I'll open a PR when it's ready
