### ISSUE TITLE
`localtimestamp with precision` test is flaky

### ISSUE THREAD

**Issue by robmwalsh** [zio/zio-sql#326]
https://app.circleci.com/pipelines/github/zio/zio-sql/338/workflows/3232b91e-0c4d-4c22-a10f-3fbc00d73452/jobs/1670

reran CI and it passed with the same commit

```
[info] - Postgres FunctionDef
[info]   - localtimestamp with precision
[info]     2020-11-25T21:48:50Z did not satisfy matchesRegex(([0-9]{4})-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9][0-9][0-9]Z)
[info] Done
[error] Failed tests:
[error] 	zio.sql.postgresql.FunctionDefSpec
[error] (postgres / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 194 s (03:14), completed Nov 25, 2020 9:49:50 PM
```

**Comment by robmwalsh** [comment]
another one
https://app.circleci.com/pipelines/github/zio/zio-sql/336/workflows/cf236dfa-a311-4222-9e6f-53c859ad1242/jobs/1661

**Comment by robmwalsh** [comment]
https://app.circleci.com/pipelines/github/zio/zio-sql/382/workflows/02ea8f27-51b4-4ca2-9aaf-ea151e16eef5/jobs/1934

**Comment by marekklis** [comment]
The same for `current_time`
```
[info] - Postgres FunctionDef
[info]   - current_time
[info]     08:19Z did not satisfy matchesRegex((2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]Z)
```
https://app.circleci.com/pipelines/github/zio/zio-sql/440/workflows/f5e8b673-9e2f-492a-af21-dd21538089f2/jobs/2306

**Comment by marekklis** [comment]
I found the source of these flaky tests.
These tests use `toString` method to make a string from `ZonedDateTime` and match it with given regular expression. These regexs assumes that `ZonedDateTime.toString` output is always in the following format `uuuu-MM-dd'T'HH:mm:ss.SSSSSSSSS` but it's not true (based od java `ZonedDateTime.toString` doc): 
```
The format used will be the shortest that outputs the full value of the time where the omitted parts are implied to be zero.
```

```
scala> ZonedDateTime.parse("2020-11-21T15:10:25.4567-04:00").toString
res5: String = 2020-11-21T15:10:25.456700-04:00

scala> ZonedDateTime.parse("2020-11-21T15:10:25.0000-04:00").toString
res6: String = 2020-11-21T15:10:25-04:00

scala> ZonedDateTime.parse("2020-11-21T15:10:00.0000-04:00").toString
res7: String = 2020-11-21T15:10-04:00
```

I'll fix these tests.

**Comment by robmwalsh** [comment]
Awesome! Thanks @marekklis

**Comment by jczuchnowski** [comment]
Solution by @marekklis has been merged. I'm closing this ticket.
