### ISSUE TITLE
should not need to include columns from all joined tables in select

### ISSUE THREAD

**Issue by unclebob418** [zio/zio-sql#39]
```scala
    val users = (int("usr_id") ++ localDate("dob") ++ string("first_name") ++ string("last_name")).table("users")
    val userId :*: dob :*: fName :*: lName :*: _ = users.columns
    val orders = (int("order_id") ++ int("usr_id") ++ localDate("order_date")).table("orders")
    val orderId :*: fkUserId :*: orderDate :*: _ = orders.columns
    val orderDetails = (int("order_id") ++ int("product_id") ++ double("quantity") ++ double("unit_price")).table("order_details")
    val fkOrderId :*: fkProductId :*: quantity :*: unitPrice :*: _ = orderDetails.columns
  /* equivalent sql
    select users.usr_id, first_name, last_name, sum(quantity * unit_price) as "total_spend"
    from users
        left join orders on users.usr_id = orders.usr_id
        left join order_details on orders.order_id = order_details.order_id
    group by users.usr_id, first_name, last_name */
val orderValues = (select {
    (Arbitrary(userId) as "usr_id") ++
      (Arbitrary(fName) as "first_name") ++
      (Arbitrary(lName) as "last_name") ++
      //(Arbitrary(orderId) as "order_id") ++ //should compile without this
      (Sum(quantity * unitPrice) as "total_spend")
  }
    from {
      users
        .join(orders)
        .on(userId === fkUserId)
        .leftOuter(orderDetails)
        .on(orderId == fkOrderId)
    })
    .groupBy(userId, fName , lName)
```
fails to compile with error:
```
type mismatch;
 found   : zio.sql.ShopSchema.Table{type TableType = zio.sql.ShopSchema.Users.users.TableType with zio.sql.ShopSchema.Orders.orders.TableType with zio.sql.ShopSchema.OrderDetails.orderDetails.TableType}
 required: zio.sql.ShopSchema.Table.Aux[zio.sql.ShopSchema.Users.users.TableType with zio.sql.ShopSchema.OrderDetails.orderDetails.TableType]
    (which expands to)  zio.sql.ShopSchema.Table{type TableType = zio.sql.ShopSchema.Users.users.TableType with zio.sql.ShopSchema.OrderDetails.orderDetails.TableType}
```
because the select statement is only using columns from `users` and `orderDetails`. it compiles if you uncomment `Arbitrary(orderId)`

**Comment by phderome** [comment]
> ```scala
>     val users = (int("usr_id") ++ localDate("dob") ++ string("first_name") ++ string("last_name")).table("users")
>     val userId :*: dob :*: fName :*: lName :*: _ = users.columns
>     val orders = (int("order_id") ++ int("usr_id") ++ localDate("order_date")).table("orders")
>     val orderId :*: fkUserId :*: orderDate :*: _ = orders.columns
>     val orderDetails = (int("order_id") ++ int("product_id") ++ double("quantity") ++ double("unit_price")).table("order_details")
>     val fkOrderId :*: fkProductId :*: quantity :*: unitPrice :*: _ = orderDetails.columns
>   /* equivalent sql
>     select users.usr_id, first_name, last_name, sum(quantity * unit_price) as "total_spend"
>     from users
>         left join orders on users.usr_id = orders.usr_id
>         left join order_details on orders.order_id = order_details.order_id
>     group by users.usr_id, first_name, last_name */
> val orderValues = (select {
>     (Arbitrary(userId) as "usr_id") ++
>       (Arbitrary(fName) as "first_name") ++
>       (Arbitrary(lName) as "last_name") ++
>       //(Arbitrary(orderId) as "order_id") ++ //should compile without this
>       (Sum(quantity * unitPrice) as "total_spend")
>   }
>     from {
>       users
>         .join(orders)
>         .on(userId === fkUserId)
>         .leftOuter(orderDetails)
>         .on(orderId == fkOrderId)
>     })
>     .groupBy(userId, fName , lName)
> ```
> 
> fails to compile with error:
> 
> ```
> type mismatch;
>  found   : zio.sql.ShopSchema.Table{type TableType = zio.sql.ShopSchema.Users.users.TableType with zio.sql.ShopSchema.Orders.orders.TableType with zio.sql.ShopSchema.OrderDetails.orderDetails.TableType}
>  required: zio.sql.ShopSchema.Table.Aux[zio.sql.ShopSchema.Users.users.TableType with zio.sql.ShopSchema.OrderDetails.orderDetails.TableType]
>     (which expands to)  zio.sql.ShopSchema.Table{type TableType = zio.sql.ShopSchema.Users.users.TableType with zio.sql.ShopSchema.OrderDetails.orderDetails.TableType}
> ```
> 
> because the select statement is only using columns from `users` and `orderDetails`. it compiles if you uncomment `Arbitrary(orderId)`

compiler had as required for select `with zio.sql.ShopSchema.OrderDetails.orderDetails.TableType` because of the named columns pertaining to that table in the select expression as `Sum(quantity * unitPrice) `, correct?
And compiler complained of found `zio.sql.ShopSchema.Orders.orders.TableType` that was not required because we didn't refer to any column of that table `Orders` in the select clause, correct? And compiler complains of what it found because prior to improving type inference with subtyping (`A1 <: A`) we drew from the table join `Orders` into the select clause?

**Comment by unclebob418** [comment]
@phderome this was probably over-complicating things - I stumbled across this while trying to make a `groupBy` example and just copied it as it was instead of simplifying it.

if we take a simpler case of wanting names of users that have ordered something we could try something like this:
```scala
  val columns = (fName as "first_name") ++ (lName as "last_name")
  val joined: ShopSchema.Table.Aux[ShopSchema.Users.users.TableType with ShopSchema.Orders.orders.TableType] = (users join orders).on(fkUserId === userId)

  val selectBuilder = select(columns)
  val query = selectBuilder.from(joined) //joined is the wrong type
```
we would get a similar error: 
```
found   : Table{type TableType = Users.users.TableType with Orders.orders.TableType}
required: Table{type TableType = Users.users.TableType}
```
this is because the `A` parameter of the `SelectBuilder` is `Users.users.TableType` (because we only used columns from the `users` table, but the `A` in the `table` we're passing it is `Users.users.TableType with Orders.orders.TableType`. The current type signature requires them to be the same:
```scala
  sealed case class SelectBuilder[F, A, B <: SelectionSet[A]](selection: Selection[F, A, B]) {
    def from(table: Table.Aux[A]): Read.Select[F, A, B] =
      Read.Select(selection, table, true, Nil)
  }
```
because `Users.users.TableType with Orders.orders.TableType` is a subtype of `Users.users.TableType` we can fix this by requiring our `table.TableType` (i.e. the `A` in `Table.Aux[A]`) be some subtype of `A` instead
```scala
def from[A1 <: A](table: Table.Aux[A1]): Read.Select[F, A1, B]
```
