### ISSUE TITLE
Add all unary operators supported by ANSI-92

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#4]
We should support the full set of unary operators, like `NOT`, `-`, `IS NULL`, etc., which are defined by ANSI-92 and / or supported by Postgres, MySQL, SQL Server, and Oracle.

These would be added as `UnaryOp` subtypes, with new methods defined in `Expr`.

If anything is unclear, please ask for more details!

**Comment by lemastero** [comment]
I will take a look. There is a nice example to follow in #41

**Comment by lemastero** [comment]
I have found following unary operators supported by MySQL, PostgreSQL, MS SQL Server, Oracle:

| operator | desc |
| ------------- | ------------- |
| ~  |  bitwise not |
| IS NULL  |   |
| IS NOT NULL |  |
| NOT | |
| - | change of sign |

`EXISTS` behave like an unary operator (EXISTS Expr) so could be added as well.
