### ISSUE TITLE
Move JdbcRunnableSpec from src/main to src/test

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#405]
This will require changing the subproject dependencies in build.sbt

**Comment by naderghanbari** [comment]
I'd like to work on this one.

**Comment by naderghanbari** [comment]
@jgoday Apologies. I only checked the comments and just realized you have an open PR for this already. Feel free to close mine :)

**Comment by jgoday** [comment]
@naderghanbari no need to apologize, your PR is more up to date anyway :+1: .

**Comment by jczuchnowski** [comment]
@jgoday @naderghanbari thank you for the work on this. I've merged the newer one as it was passing all the checks.
