### ISSUE TITLE
Add FunctionDef for functions in ANSI-92

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#5]
We should support the full set of standard functions, which are defined by ANSI-92 and / or supported by Postgres, MySQL, SQL Server, and Oracle.

These would be added as `FunctionDef` values, in the companion object of `FunctionDef`.

If anything is unclear, please ask for more details!

**Comment by jczuchnowski** [comment]
@marekklis is there anything more to do here?

**Comment by marekklis** [comment]
I thought about conversion function but I checked that usage of that function is different for the different DB servers.
So, I think there is nothing to add.
