### ISSUE TITLE
Support INSERT queries

### ISSUE THREAD

**Issue by lemastero** [zio/zio-sql#55]
There is no support for the INSERT clause.

**Comment by jczuchnowski** [comment]
Requires to create `InsertModule` similar to `SelectModule`, `UpdateModule` and `DeleteModule` and declare analogical InsertExecutor in `jdbc.scala` module.
Live implementation of the executor can be done in a different PR.

**Comment by jotarada** [comment]
i can pick this one

**Comment by jczuchnowski** [comment]
Implemented https://github.com/zio/zio-sql/pull/550
