### ISSUE TITLE
enrich Expr with name

### ISSUE THREAD

**Issue by sviezypan** [zio/zio-sql#564]
Currently there exists `as` method on `Expr ` that returns `Selection`
```
import AggregateDef._
val orderCount : Selection[F, orders.TableType, _] = Count(orderId) as "orderCount"
```
However it would be beneficial if orderCount returned Expr enriched with name, so that we can reuse it in place where Expr is required, like:
```
val orderCount : Expr[F, orders.TableType, Int] = Count(orderId) as "orderCount"
select(orderCount)
          .from(orders)
          .groupBy(fkCustomerId)
          .orderBy(Desc(orderCount))
```
At the moment code above results in compile time error, since `orderBy` clause expects an `Expr`.

**Comment by radutoev** [comment]
Would like to work on this if possible.

**Comment by sviezypan** [comment]
Seems that current implementation, which in the meantime already returns `Expr` is good enough.
```
    def as[B1 >: B](name: String): Expr[F, A, B1] = {
      val _ = name
      self
    }
```   
This naming of column has no effect on sql output and how zio sql user works with the returned data, so we can safely ignore `name`.
