### ISSUE TITLE
Add AggregationDef for aggregations supported by ANSI-92

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#6]
We should support the full set of standard aggregations, such as `COUNT`, `SUM`, etc, which are defined by ANSI-92 and / or supported by Postgres, MySQL, SQL Server, and Oracle.

These would be added as `AggregationDef` values, in the companion object of `AggregationDef`.

If anything is unclear, please ask for more details!

**Comment by jczuchnowski** [comment]
Looks like this is done. If there are more missing functions we can do it in another Issue/PR.
