### ISSUE TITLE
In ReadExecutor, verify a statement execution returns a ResultSet

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#63]
Currently, the boolean value returned from `Statement#execute` in `ReadExecutor` is ignored. It should be checked, and if `false`, it means there is no result set being returned, which we should handle appropriately rather than just calling `getResultSet()`.

**Comment by TobiasPfeifer** [comment]
even `SELECT NULL LIMIT 0;` returns a `ResultSet` (empty). I couldn't figure out a way to get `Statement#execute` return `false` for a `SELECT`. And I don't think someone can sneak in an `update` into a `Read[A]` that gets reflected as having no `ResultSet`

However just to handle all corner cases I would suggest to return an empty result stream.

I'll give this a try
