### ISSUE TITLE
Add `radians` function to MysqlSqlModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#650]
Add support for function `degrees` described in the MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_radians).

Add function to MysqlFunctionDef in MysqlSqlModule
Add test in FunctionDefSpec

**Comment by walesho** [comment]
I would like to work on this.

**Comment by jczuchnowski** [comment]
Done.
