### ISSUE TITLE
Add `rand` function to MysqlSqlModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#651]
Add support for function `rand` described in the MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_rand).

Add function to MysqlFunctionDef in MysqlSqlModule
Add test in FunctionDefSpec

**Comment by gantu** [comment]
I would like to work on this issue.

**Comment by jczuchnowski** [comment]
Done.
