### ISSUE TITLE
Add `makedate` function to MysqlSqlModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#655]
Add support for function `makedate` described in the MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_makedate).

Add function to MysqlFunctionDef in MysqlSqlModule
Add test in FunctionDefSpec

**Comment by peixunzhang** [comment]
I will take this ticket.

**Comment by jczuchnowski** [comment]
Done in https://github.com/zio/zio-sql/pull/671
