### ISSUE TITLE
Add `maketime` function to MysqlSqlModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#656]
Add support for function `maketime` described in the MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_maketime).

Add function to MysqlFunctionDef in MysqlSqlModule
Add test in FunctionDefSpec

**Comment by sarahotoole** [comment]
I'll take this one ☺️

**Comment by jczuchnowski** [comment]
Done.
