### ISSUE TITLE
Add `uuid` function to MysqlSqlModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#657]
Add support for function `uuid` described in the MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid).

Add function to MysqlFunctionDef in MysqlSqlModule
Add test in FunctionDefSpec

**Comment by vidyasankarv** [comment]
I would like to work  on this

**Comment by jczuchnowski** [comment]
Done.
