### ISSUE TITLE
Add `hex` function to MysqlSqlModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#659]
Add support for function `hex` described in the MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_hex).

Add function to MysqlFunctionDef in MysqlSqlModule
Add test in FunctionDefSpec

**Comment by ujali** [comment]
I would like to work on this!

**Comment by jczuchnowski** [comment]
Done. Thank you @ujali !
