### ISSUE TITLE
ExecuteBuilder in ReadExecutor only supports arities 1-2

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#66]
Support for arities 1-20 should be easy to add by following the pattern established in `ExecuteBuilder`.

Please request clarification if anything is unclear.

**Comment by phderome** [comment]
fyi: The quill project goes through some pains to have names of Scala variables in the lambda (`to` in ZIO-SQL) being tied when possible to column aliases with the queries. This is a valuable feature.

**Comment by jacobBaumbach** [comment]
I would like to give this one a go
