### ISSUE TITLE
Adopt ZIO JDBC model for transactions

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#665]
**ISSUE**

ZIO SQL was created before ZIO 2. As a result, it utilizes an older pattern for transactions, which involves the `ZTransaction` type. This means that users must be painfully aware of transaction boundaries and transaction types, and non-transaction types must be lifted up into `ZTransaction`.

**SOLUTION**

With layers as eliminators, ZIO JDBC has pioneered a new way to think about transactions, foreshadowing the work done in ZIO 2 which replaces `ZManaged` with scoped ZIO effects. These new ways of dealing with transactions and resources will permit a much cleaner way to model transactions in ZIO SQL. In particular, transactions can become ordinary `ZIO` effects, but with an environment parameter that will be eliminated by a `transaction` operator.

Possibly the end-user API can look like this:

```scala
val myQuery : ZIO[SqlTransaction, Throwable, Result] = ???

transaction { myQuery } // ZIO[Any, Throwable, Result]
```

**IMPACT**

Making this change will bring ZIO SQL up to the latest standards for dealing with resources and transactions in the ZIO 2 ecosystem, and make use of the library by end-users much easier. 

**WHERE TO LOOK**

Study the design of ZIO JDBC and ZIO 2 scopes. Then search the code base for `ZTransaction`, which will need to be replaced by an ordinary `ZIO` effect, where the environment is used to keep track of transaction information.

**PROBLEMMATIC ISSUES**

It may be necessary to understand scopes and to take a peek at ZIO JDBC in order to complete this issue successfully. Reach out to maintainers for hints or pairing.

**Comment by mschuwalow** [comment]
I'll take this one
