### ISSUE TITLE
Pull out SQL rendering into dialect-specific modules

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#67]
SQL rendering will be dialect-specific. We could have generic rendering but that should be only for debugging / diagnostics.

Now that we have separate modules for Postgres, SQL Server, Oracle, and MySQL, we should create traits for each of these dialects, and implement SQL rendering functionality there.

**Comment by jczuchnowski** [comment]
This has been addressed by @robmwalsh in https://github.com/zio/zio-sql/pull/100
