### ISSUE TITLE
Implement proper SQL rendering for Postgres

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#72]
This rendering should be able to take one of the core data types (`Read`, `Update`, `Delete`, `Insert`) and render to a string that constitutes a valid SQL query for the database, taking care to escape strings properly and otherwise be robust to injection attacks.

**Comment by jczuchnowski** [comment]
Splitting this into: https://github.com/zio/zio-sql/issues/150, https://github.com/zio/zio-sql/issues/151, https://github.com/zio/zio-sql/issues/152
