### ISSUE TITLE
Implement proper SQL rendering for MySQL

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#73]
This rendering should be able to take one of the core data types (`Read`, `Update`, `Delete`, `Insert`) and render to a string that constitutes a valid SQL query for the database, taking care to escape strings properly and otherwise be robust to injection attacks.

**Comment by jczuchnowski** [comment]
Splitting this into: https://github.com/zio/zio-sql/issues/149, https://github.com/zio/zio-sql/issues/156, https://github.com/zio/zio-sql/issues/157, https://github.com/zio/zio-sql/issues/158
