### ISSUE TITLE
Implement proper SQL rendering for SQL Server

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#74]
This rendering should be able to take one of the core data types (`Read`, `Update`, `Delete`, `Insert`) and render to a string that constitutes a valid SQL query for the database, taking care to escape strings properly and otherwise be robust to injection attacks.

**Comment by phderome** [comment]
fyi: `prepareStatement` is one way to address the issue at JDBC level but it comes at a cost of extra roundtrip to database.

**Comment by robmwalsh** [comment]
I'll take this one

**Comment by jczuchnowski** [comment]
Splitting this into: https://github.com/zio/zio-sql/issues/159, https://github.com/zio/zio-sql/issues/160, https://github.com/zio/zio-sql/issues/161
