### ISSUE TITLE
Add support for executing to tuples

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#79]
Right now we can execute read queries using `execute(query).to(caseClass)` (using machinery in `Jdbc` in the JDBC module), which is convenient in some cases, but in other cases, it's more convenient to use tuple representation.

We should also support `execute(query).toTuple`. 

This could be done using some sort of type class:

```scala
sealed trait ToTuple[A] {
  type Output

  def toTuple(a: A): Output
}  
object ToTuple {
  type Aux[A, Output0] = ToTuple { type Output = Output0 }

  implicit def toTuple2[A, B]: ToTuple.Aux[(A, (B, Unit)) {
    type Output = (A, B)

    def toTuple(t: (A, (B, Unit))): Output = (t._1, t._2._1)
  }
  ...
}
```

which could be used as follows in the execute builder:

```scala
...
def toTuple[E <: ToTuple[A]](implicit ev: E): Stream[Exception, ev.Output] = ???
...
```

This is only a rough sketch and tests must be done to ensure it infers correctly.

**Comment by sviezypan** [comment]
This was done as part of #577
