### ISSUE TITLE
Add rendering to SQL for core data types

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#8]
We should add rendering to SQL for core data types, with several options:

```scala
sealed trait RenderMode
object RenderMode {
  case object Compact
  final case class Pretty(indent: Int)
}
...

// On all SQL types
def render(mode: RenderMode): String = /* calls render builder */

private[zio] def renderBuilder(builder: StringBuilder: mode: RenderMode): Unit
```

The use of `StringBuilder` is for performance reasons and can be hidden as a private implementation detail.

Note that extreme care should be taken when rendering strings into SQL, as they must be properly escaped, to avoid SQL injection attacks.

**Comment by unclebob418** [comment]
I'll give this one a go

**Comment by jdegoes** [comment]
Wow, that's awesome. Good luck and let me know if you need any help!

**Comment by unclebob418** [comment]
I'll finish watching the video before I do too much on this. is the intention to return `PreparedStatement`s at the top level? I'd think ideally we don't execute queries that aren't parameterised.

**Comment by jdegoes** [comment]
I would aim for a simple string rendering. Currently we don't have parameterized queries, which would be necessary to generate `PreparedStatement`. Also I think the core of the library should be usable without JDBC or even on Javascript.

We could consider this string rendering a step toward JDBC and also extremely useful for diagnostics / debugging / development.

**Comment by jczuchnowski** [comment]
Closing this. @robmwalsh did a lot of work here. The rendering is now database specific.
