### ISSUE TITLE
Unable to run example code

### ISSUE THREAD

**Issue by davidleacock** [zio/zio-sql#838]
Apologies for posting this here but could not find other forms available for this discussion. I'm unable to run the example code. I get an error "No implicits found for parameter schema: Schema.Record[Person]" for the defineTable() method.  I've copied the code example as shown.  Does this mean that zio.schema isnt generating the appropriate code for me?   Thank you for your help

```
import zio.schema.Schema
import zio.sql.postgresql.PostgresJdbcModule

object playground extends PostgresJdbcModule {

  final case class Person(name: String, age: Int)
  implicit val schema: Schema[Person] = DeriveSchema.gen[Person]

  val person = defineTable[Person]. // error is here

}
```

**Comment by sviezypan** [comment]
hi @davidleacock try to remove Schema[Person[ type and let compiler infer value for you.
So:
```
  implicit val schema = DeriveSchema.gen[Person]
```
Let me know if that helps

**Comment by davidleacock** [comment]
Thank you for the response.  Sadly that doesn't resolve it. I actually added the type an an attempt to fix it before.  Also followed the zio-schema docs to try and contruct the schema differently and no luck.  

Here are my dependencies if this helps. I've tried older versions of zio-sql and included schema as well 

```
lazy val zioVersion = "2.0.0"
libraryDependencies ++= Seq(
  "dev.zio" %% "zio" % zioVersion,
  "dev.zio" %% "zio-test" % zioVersion,
  "io.d11" %% "zhttp" % "2.0.0-RC10",
  "dev.zio" %% "zio-test-sbt" % zioVersion,
  "dev.zio" %% "zio-json" % "0.3.0-RC8",
  "dev.zio" %% "zio-streams" % zioVersion,
  "dev.zio" %% "zio-test-junit" % zioVersion,
  "dev.zio" %% "zio-sql-postgres" % "0.1.2",
//  "dev.zio" %% "zio-schema" % "0.4.8"
)
```

**Comment by davidleacock** [comment]
Thank you for your response. I apologize, this appears to be an issue with IntelliJ.  I'm able to command line compile and access the person table but the error still shows so its a problem with the IDE.  Closing the issue.
