### ISSUE TITLE
Add various transformation methods to Expr

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-sql#9]
Some generic folding and transformation methods will be useful to add to `Expr`, including:

 - bottom-up transformations, with and without context and state
 - top-down transformations, with and without context and state
 - folding bottom-up, with state
 - folding top-down, with state

**Comment by adamgfraser** [comment]
I will work on this.

**Comment by adamgfraser** [comment]
Can you say a little more about how you envision this working? It seems like given the number of cases and the fact that some of them involve types like `FunctionDef` and `AggregationDef` that transform the types it is going to be hard to fold over or transform an `Expr` without the user providing a way to interpret all these different things.

**Comment by jdegoes** [comment]
There are 2 ways to approach it.

First is to make traits like `ExprVisitor[Z]` for folding:

```scala
trait ExprVisitor[Z] {
  def binary[F1, F2, A, B](left: Expr[F1, A, B], right: Expr[F2, A, B], op: BinaryOp[B]): Z 
  ...
}
```

And similar ones for transformation.

Other way is to encode `Expr` using specialized fixpoint, like `Spec` in ZIO Test, such that you have an `ExprCase` which does not utilize recursion, and `Expr` introduces recursion in the usual way.

The latter way is more significant in scope but also cleaner and may be less work over the long term.

**Comment by adamgfraser** [comment]
Okay, let me work on the fixed point approach.

**Comment by sviezypan** [comment]
I know this is an old ticket but I recently opened a related issue with composing `Exprs`.
#583 
If you have idea what operator is missing, please let me know, it would help me get started.
